### ISSUE TITLE
An error occurred during use, please help check it.

### ISSUE THREAD

**Issue by hyoseong1989** [HNIdesu/BookliveDumper#1]
When I try books with a capacity exceeding 100MB, an error occurs and the following message appears:

(process:19184): GLib-GIO-WARNING **: 13:03:14.731: _g_dbus_worker_do_read_cb: error determining bytes needed: Blob indicates that message exceeds maximum message length (128MiB)

Can you help fix it so that it can save books without capacity limitations.
![1](https://github.com/user-attachments/assets/03b1bf84-dc5d-44b6-b2f3-476e789b38a9)

**Comment by HNIdesu** [comment]
I understand. To better assist you, I need to know the operating system of your device. I've only tested my application on Windows and am not familiar with how it performs on other platforms.

**Comment by hyoseong1989** [comment]
Thank you for your reply. My operating system is Windows 11 Professional Edition.
The Python I installed is:

certifi==2022.12.7
charset-normalizer==3.0.1
frida==16.5.1
idna==3.4
lxml==4.9.2
requests==2.28.2
urllib3==1.26.14





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HNIdesu/BookliveDumper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月11日(星期三) 下午2:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HNIdesu/BookliveDumper] An error occurred during use, please help check it. (Issue #1)





 
I understand. To better assist you, I need to know the operating system of your device. I've only tested my application on Windows and am not familiar with how it performs on other platforms.

**Comment by HNIdesu** [comment]
It seems there's a size limit on data transfer between Python and Frida. I've modified the code to send data in chunks. You can try the code on the `fix-issue-1` branch, and if everything works fine, I'll merge it into the main branch.

**Comment by hyoseong1989** [comment]
Thank you for your help. I just tested it and it shows an error on line 53


F:\download\BookliveDumper-fix-issue-1\src&gt;python booklive-dumper.py
&nbsp; File "F:\download\BookliveDumper-fix-issue-1\src\booklive-dumper.py", line 53
&nbsp; &nbsp; class CustomList[T]:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^
SyntaxError: invalid syntax





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月11日(星期三) 下午4:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HNIdesu/BookliveDumper] An error occurred during use, please help check it. (Issue #1)














 
It seems there's a size limit on data transfer between Python and Frida. I've modified the code to send data in chunks. You can try the code on the fix-issue-1 branch, and if everything works fine, I'll merge it into the main branch.

**Comment by HNIdesu** [comment]
You may need to update Python. The script was tested using Python 3.12.4.
